name = "1.19 FPS Vanilla"
author = "Toasty"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "141301d1f6760c98eaa70796566e1f17a8ae9c04181c5378d4419b50b8bf6201"

[versions]
minecraft = "1.19.3"
quilt = "0.18.1-beta.25"
