name = "1.19 FPS Vanilla"
author = "Toasty"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "355a72b5a0b952c2c3fc02fa7e9b47681d7466be3378169c9ed24f1207ba9628"

[versions]
minecraft = "1.19.3"
quilt = "0.18.1-beta.25"
