name = "1.19 FPS Vanilla"
author = "Toasty"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0dd030d0afc668415dc52eae043205141804cd6ce5faa4d9db81cc4fa5a65a2f"

[versions]
minecraft = "1.19.3"
quilt = "0.18.1-beta.25"
