name = "Create Pack"
author = "Toasty"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "16fe13db212d3a3845235643ac1143c949857f3c391591647b194494dddea14e"

[versions]
forge = "40.0.0"
minecraft = "1.18.2"
