name = "Create Pack"
author = "Toasty"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f65f0bb5d18028dd9a3c38011c2286c0609c5587ab9a3e3e6830e288395c872b"

[versions]
forge = "40.1.92"
minecraft = "1.18.2"
