name = "1 . 19 FPS Vanilla Replay Mod"
author = "Toasty"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "173eca2bb102e5c6150332b77a226724e33d9c828b6c992d3cbaaf79db2250a8"

[versions]
fabric = "0.14.10"
minecraft = "1.19.2"
